// examples/svelte/src/lib/Login.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { useNavigate } from "svelte-navigator";
  import { register } from '@teamhanko/hanko-elements';

  const api = import.meta.env.VITE_HANKO_API;

  const navigate = useNavigate();
  let element;

  const redirectToTodos = () => {
    navigate('/todo');
  };

  onMount(async () => {
    register({ shadow: true }).catch((e) => {
      console.error(e)
    });

    element?.addEventListener('hankoAuthSuccess', redirectToTodos);
  });

  onDestroy(() => {
    element?.removeEventListener('hankoAuthSuccess', redirectToTodos);
  });
</script>

<div class="content">
  <hanko-auth bind:this={element} {api} lang="en"/>
</div>

<style>
  .content {
      padding: 24px;
      border-radius: 17px;
      color: black;
      background-color: white;
      width: 500px;
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
  }
</style>

// examples/angular/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { environment } from '../../environments/environment';
import { Router } from '@angular/router';
import { register } from '@teamhanko/hanko-elements/hanko-auth';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  api = environment.hankoApi;

  constructor(private router: Router) {
    register({ shadow: true }).catch((e) => console.error(e));
  }

  redirectToTodo() {
    this.router.navigate(['/todo']);
  }
}

<div class="content">
  <hanko-auth
    (hankoAuthSuccess)="redirectToTodo()"
    [api]="api"
  ></hanko-auth>
</div>
