// examples/angular/src/app/todo/todo.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Todos, TodoService } from '../services/todo.service';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['../app.component.css', './todo.component.css'],
})
export class TodoComponent implements OnInit {
  todos: Todos = [];
  error: Error | undefined;
  description = '';

  changeDescription(event: any) {
    this.description = event.target.value;
  }

  changeCheckbox(event: any) {
    const { currentTarget } = event;
    this.patchTodo(currentTarget.value, currentTarget.checked);
  }

  constructor(private todoService: TodoService, private router: Router) {}

  ngOnInit(): void {
    this.listTodos();
  }

  addTodo(event: any) {
    event.preventDefault();
    const entry = { description: this.description, checked: false };

    this.todoService
      .addTodo(entry)
      .then((res) => {
        if (res.status === 401) {
          this.router.navigate(['/']).catch((e) => (this.error = e));
          return;
        }

        this.description = '';
        this.listTodos();

        return;
      })
      .catch((e) => {
        this.error = e;
      });
  }

  patchTodo(id: string, checked: boolean) {
    this.todoService
      .patchTodo(id, checked)
      .then((res) => {
        if (res.status === 401) {
          this.router.navigate(['/']).catch((e) => (this.error = e));
          return;
        }

        this.listTodos();

        return;
      })
      .catch((e) => {
        this.error = e;
      });
  }

  listTodos() {
    this.todoService
      .listTodos()
      .then((res) => {
        if (res.status === 401) {
          this.router.navigate(['/']).catch((e) => (this.error = e));
          return;
        }

        return res.json();
      })
      .then((todo) => {
        if (todo) {
          this.todos = todo;
        }
      })
      .catch((e) => {
        this.error = e;
      });
  }

  deleteTodo(id: string) {
    this.todoService
      .deleteTodo(id)
      .then((res) => {
        if (res.status === 401) {
          this.router.navigate(['/']).catch((e) => (this.error = e));
          return;
        }

        this.listTodos();

        return;
      })
      .catch((e) => {
        this.error = e;
      });
  }

  logout() {
    this.todoService
      .logout()
      .then(() => {
        this.router.navigate(['/']).catch((e) => (this.error = e));
        return;
      })
      .catch((e) => this.error = e);
  }

  profile() {
    this.router.navigate(['/profile']).catch((e) => (this.error = e));
  }
}

<nav class="nav">
  <button (click)="logout()" class="button">logout</button>
</nav>
<div class="content">
  <h1 class="headline">Todos</h1>
  <div class="error">{{ error?.message }}</div>
  <form (submit)="addTodo($event)" class="form">
    <input
      required
      class="input"
      type="text"
      value="{{ description }}"
      (change)="changeDescription($event)"
    />
    <button type="submit" class="button">+</button>
  </form>
  <div class="list">
    <div *ngFor="let todo of todos; index as id" class="item">
      <input
        class="checkbox"
        id="{{ id.toString(10) }}"
        type="checkbox"
        value="{{ id }}"
        [checked]="todo.checked"
        (change)="changeCheckbox($event)"
      />
      <label class="description" for="{{ id.toString(10) }}">{{
        todo.description
      }}</label>
      <button class="button" (click)="deleteTodo(id)">×</button>
    </div>
  </div>
</div>

// frontend/examples/react/src/Todo.tsx
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { TodoClient, Todos } from "./TodoClient";
import styles from "./Todo.module.css";

const api = process.env.REACT_APP_TODO_API!;

function Todo() {
  const navigate = useNavigate();
  const [todos, setTodos] = useState<Todos>([]);
  const [description, setDescription] = useState<string>("");
  const [error, setError] = useState<Error | null>(null);
  const client = useMemo(() => new TodoClient(api), []);

  const addTodo = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const todo = { description, checked: false };

    client
      .addTodo(todo)
      .then((res) => {
        if (res.status === 401) {
          navigate("/");
          return;
        }

        setDescription("");
        listTodos();

        return;
      })
      .catch(setError);
  };

  const listTodos = useCallback(() => {
    client
      .listTodos()
      .then((res) => {
        if (res.status === 401) {
          navigate("/");
          return;
        }

        return res.json();
      })
      .then((todo) => {
        if (todo) {
          setTodos(todo);
        }
      })
      .catch(setError);
  }, [client, navigate]);

  const patchTodo = (id: string, checked: boolean) => {
    client
      .patchTodo(id, checked)
      .then((res) => {
        if (res.status === 401) {
          navigate("/");
          return;
        }

        listTodos();

        return;
      })
      .catch(setError);
  };

  const deleteTodo = (id: string) => {
    client
      .deleteTodo(id)
      .then((res) => {
        if (res.status === 401) {
          navigate("/");
          return;
        }

        listTodos();

        return;
      })
      .catch(setError);
  };

  const logout = () => {
    client
      .logout()
      .then(() => {
        navigate("/");
        return;
      })
      .catch(setError);
  };

  const profile = () => {
    navigate("/profile");
  }

  const changeDescription = (event: React.ChangeEvent<HTMLInputElement>) => {
    setDescription(event.currentTarget.value);
  };

  const changeCheckbox = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { currentTarget } = event;
    patchTodo(currentTarget.value, currentTarget.checked);
  };

  useEffect(() => {
    listTodos();
  }, [listTodos]);

  return (
    <>
      <nav className={styles.nav}>
        <button onClick={logout} className={styles.button}>
          Logout
        </button>
        <button onClick={profile} className={styles.button}>
          Profile
        </button>
        <button disabled className={styles.button}>
          Todos
        </button>
      </nav>
      <div className={styles.content}>
        <h1 className={styles.headline}>Todos</h1>
        <div className={styles.error}>{error?.message}</div>
        <form onSubmit={addTodo} className={styles.form}>
          <input
            required
            className={styles.input}
            type={"text"}
            value={description}
            onChange={changeDescription}
          />
          <button type={"submit"} className={styles.button}>
            +
          </button>
        </form>
        <div className={styles.list}>
          {todos.map((todo, index) => (
            <div className={styles.item} key={index}>
              <input
                className={styles.checkbox}
                id={todo.todoID}
                type={"checkbox"}
                value={todo.todoID}
                checked={todo.checked}
                onChange={changeCheckbox}
              />
              <label className={styles.description} htmlFor={todo.todoID}>
                {todo.description}
              </label>
              <button className={styles.button} onClick={() => deleteTodo(todo.todoID!)}>
                ×
              </button>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}

export default Todo;
