// frontend/examples/nextjs-app/components/HankoAuth.tsx
"use client";

import { Hanko, register } from "@teamhanko/hanko-elements";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";

interface Props {
  setError(error: Error): void;
}

function HankoAuth({ setError }: Props) {
  const router = useRouter();
  const [hankoClient, setHankoClient] = useState<Hanko>();
  const api = process.env.NEXT_PUBLIC_HANKO_API!;

  const redirectToTodos = useCallback(() => {
    router.push("/todo");
  }, [router]);

  useEffect(() => {
    setHankoClient(new Hanko(api));
  }, [api]);

  useEffect(() => {
    register(api).catch(setError);
  }, [setError, api]);

  useEffect(() => {
    if (hankoClient) {
      hankoClient.onSessionCreated(() => {
        redirectToTodos();
      });
    }
  }, [hankoClient, redirectToTodos]);

  return <hanko-auth />;
}

export default HankoAuth;

// examples/vue/src/components/HankoAuth.vue
<script setup>
import { useRouter } from "vue-router";
import { register } from "@teamhanko/hanko-elements/hanko-auth";
import { onMounted } from "vue";

onMounted(() => {
  register({ shadow: true }).catch((e) => console.error(e));
});

const api = import.meta.env.VITE_HANKO_API;

const router = useRouter();

const redirectToTodo = () => {
  router.push({ path: "/todo" });
};
</script>

<template>
  <hanko-auth @hankoAuthSuccess="redirectToTodo" :api="api" />
</template>
