// examples/nextjs/components/HankoAuth.tsx
import { register } from "@teamhanko/hanko-elements";
import { useCallback, useEffect } from "react";
import { useRouter } from "next/router";

const api = process.env.NEXT_PUBLIC_HANKO_API!;

function HankoAuth() {
  const router = useRouter();

  const redirectToTodos = useCallback(() => {
    router.replace("/todo");
  }, [router]);

  useEffect(() => {
    register({ shadow: true }).catch((e) => console.error(e));
  }, []);

  useEffect(() => {
    document.addEventListener("hankoAuthSuccess", redirectToTodos);
    return () =>
      document.removeEventListener("hankoAuthSuccess", redirectToTodos);
  }, [redirectToTodos]);

  return <hanko-auth api={api} lang="en"/>;
}

export default HankoAuth;

// examples/vue/src/components/HankoAuth.vue
<script setup>
import { useRouter } from "vue-router";
import { register } from "@teamhanko/hanko-elements/hanko-auth";
import { onMounted } from "vue";

onMounted(() => {
  register({ shadow: true }).catch((e) => console.error(e));
});

const api = import.meta.env.VITE_HANKO_API;

const router = useRouter();

const redirectToTodo = () => {
  router.push({ path: "/todo" });
};
</script>

<template>
  <hanko-auth @hankoAuthSuccess="redirectToTodo" :api="api" />
</template>
