// examples/nextjs/pages/todo.tsx
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { NextPage } from "next";
import { useRouter } from "next/router";
import { TodoClient, TodoList } from "../util/TodoClient";
import styles from "../styles/Todo.module.css";

const api = process.env.NEXT_PUBLIC_BACKEND!;

const Todo: NextPage = () => {
  const client = useMemo(() => new TodoClient(api), []);
  const router = useRouter();

  const [todos, setTodos] = useState<TodoList>([]);
  const [description, setDescription] = useState<string>("");
  const [error, setError] = useState<Error | null>(null);

  const addTodo = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const entry = { description, checked: false };

    client
      .addTodo(entry)
      .then((res) => {
        if (res.status === 401) {
          router.replace("/").catch((e) => setError(e));
          return;
        }

        setDescription("");
        listTodos();

        return;
      })
      .catch((e) => {
        setError(e);
      });
  };

  const listTodos = useCallback(() => {
    client
      .listTodos()
      .then((res) => {
        if (res.status === 401) {
          router.push("/").catch((e) => setError(e));
          return;
        }

        return res.json();
      })
      .then((t) => {
        if (t) {
          setTodos(t);
        }
      })
      .catch((e) => {
        setError(e);
      });
  }, [client, router]);

  const patchTodo = (id: number, checked: boolean) => {
    client
      .patchTodo(id, checked)
      .then((res) => {
        if (res.status === 401) {
          router.push("/").catch((e) => setError(e));
          return;
        }

        listTodos();

        return;
      })
      .catch((e) => {
        setError(e);
      });
  };

  const deleteTodo = (id: number) => {
    client
      .deleteTodo(id)
      .then((res) => {
        if (res.status === 401) {
          router.push("/").catch((e) => setError(e));
          return;
        }

        listTodos();

        return;
      })
      .catch((e) => {
        setError(e);
      });
  };

  const logout = () => {
    client
      .logout()
      .then(() => {
        router.push("/").catch((e) => setError(e));
        return;
      })
      .catch((e) => {
        setError(e);
      });
  };

  const changeDescription = (event: React.ChangeEvent<HTMLInputElement>) => {
    setDescription(event.currentTarget.value);
  };

  const changeCheckbox = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { currentTarget } = event;
    patchTodo(Number(currentTarget.value), currentTarget.checked);
  };

  useEffect(() => {
    listTodos();
  }, [listTodos]);

  return (
    <>
      <nav className={styles.nav}>
        <button onClick={logout} className={styles.button}>
          logout
        </button>
      </nav>
      <div className={styles.content}>
        <h1 className={styles.headline}>Todos</h1>
        <div className={styles.error}>{error?.message}</div>
        <form onSubmit={addTodo} className={styles.form}>
          <input
            required
            className={styles.input}
            type={"text"}
            value={description}
            onChange={changeDescription}
          />
          <button type={"submit"} className={styles.button}>
            +
          </button>
        </form>
        <div className={styles.list}>
          {todos.map((t, id) => (
            <div className={styles.item} key={id}>
              <input
                className={styles.checkbox}
                id={id.toString(10)}
                type={"checkbox"}
                value={id}
                checked={t.checked}
                onChange={changeCheckbox}
              />
              <label className={styles.description} htmlFor={id.toString(10)}>
                {t.description}
              </label>
              <button className={styles.button} onClick={() => deleteTodo(id)}>
                ×
              </button>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default Todo;

// examples/angular/src/app/todo/todo.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { TodoList, TodoService } from '../services/todo.service';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css'],
})
export class TodoComponent implements OnInit {
  todos: TodoList = [];
  error: Error | undefined;
  description = '';

  changeDescription(event: any) {
    this.description = event.target.value;
    console.log(this.description);
  }

  changeCheckbox(event: any) {
    const { currentTarget } = event;
    this.patchTodo(Number(currentTarget.value), currentTarget.checked);
  }

  constructor(private todoService: TodoService, private router: Router) {}

  ngOnInit(): void {
    this.listTodos();
  }

  addTodo(event: any) {
    event.preventDefault();
    const entry = { description: this.description, checked: false };

    this.todoService
      .addTodo(entry)
      .then((res) => {
        if (res.status === 401) {
          this.router.navigate(['/']).catch((e) => (this.error = e));
          return;
        }

        this.description = '';
        this.listTodos();

        return;
      })
      .catch((e) => {
        this.error = e;
      });
  }

  patchTodo(id: number, checked: boolean) {
    this.todoService
      .patchTodo(id, checked)
      .then((res) => {
        if (res.status === 401) {
          this.router.navigate(['/']).catch((e) => (this.error = e));
          return;
        }

        this.listTodos();

        return;
      })
      .catch((e) => {
        this.error = e;
      });
  }

  listTodos() {
    this.todoService
      .listTodos()
      .then((res) => {
        if (res.status === 401) {
          this.router.navigate(['/']).catch((e) => (this.error = e));
          return;
        }

        return res.json();
      })
      .then((t) => {
        if (t) {
          this.todos = t;
        }
      })
      .catch((e) => {
        this.error = e;
      });
  }

  deleteTodo(id: number) {
    this.todoService
      .deleteTodo(id)
      .then((res) => {
        if (res.status === 401) {
          this.router.navigate(['/']).catch((e) => (this.error = e));
          return;
        }

        this.listTodos();

        return;
      })
      .catch((e) => {
        this.error = e;
      });
  }

  logout() {
    this.todoService
      .logout()
      .then(() => {
        this.router.navigate(['/']).catch((e) => (this.error = e));
        return;
      })
      .catch((e) => {
        console.error(e);
      });
  }
}

<nav class="nav">
  <button (click)="logout()" class="button">logout</button>
</nav>
<div class="content">
  <h1 class="headline">Todos</h1>
  <div class="error">{{ error?.message }}</div>
  <form (submit)="addTodo($event)" class="form">
    <input
      required
      class="input"
      type="text"
      value="{{ description }}"
      (change)="changeDescription($event)"
    />
    <button type="submit" class="button">+</button>
  </form>
  <div class="list">
    <div *ngFor="let todo of todos; index as id" class="item">
      <input
        class="checkbox"
        id="{{ id.toString(10) }}"
        type="checkbox"
        value="{{ id }}"
        [checked]="todo.checked"
        (change)="changeCheckbox($event)"
      />
      <label class="description" for="{{ id.toString(10) }}">{{
        todo.description
      }}</label>
      <button class="button" (click)="deleteTodo(id)">×</button>
    </div>
  </div>
</div>
