// frontend/examples/vue/src/components/SessionExpiredModal.vue
<script setup lang="ts">
import { ref } from "vue";
import type { Ref } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();
const modal = ref<HTMLDialogElement | null>(null);
const error: Ref<Error | null> = ref(null);

const show = () => {
  modal.value?.showModal();
};

const redirectToLogin = () => {
  router.push("/").catch((e) => (error.value = e));
};

defineExpose({
  show,
});
</script>

<template>
  <hanko-events @onSessionExpired="show()"></hanko-events>
  <dialog ref="modal" id="session-expired-modal">
    <div class="error">{{ error?.message }}</div>
    Please login again.<br /><br />
    <button @click="redirectToLogin()">Login</button>
  </dialog>
</template>

// frontend/examples/angular/src/app/modal/session-expired-modal.component.ts
import { Component, ElementRef, ViewChild } from "@angular/core";
import { Router } from '@angular/router';
import { HankoService } from "../services/hanko.services";

@Component({
  selector: 'app-session-expired-modal',
  templateUrl: './session-expired-modal.component.html',
  styleUrls: ['../app.component.css'],
})
export class SessionExpiredModalComponent {
  @ViewChild('modal') modal?: ElementRef<HTMLDialogElement>;
  error?: Error;

  constructor(private hankoService: HankoService, private router: Router) {}

  redirectToLogin() {
    this.router.navigate(['/']).catch((e) => (this.error = e));
  }

  show() {
    this.modal?.nativeElement.showModal();
  }
}

<hanko-events (onSessionExpired)="openSessionExpiredModal()"></hanko-events>
<dialog id="session-expired-modal">
  <div class="error">{{ error?.message }}</div>
  Please login again.<br><br>
  <button (click)="redirectToLogin()">Login</button>
</dialog>
