// frontend/examples/svelte/src/lib/Profile.svelte
<script lang="ts">
    import { useNavigate } from "svelte-navigator";
    import { Hanko } from "@teamhanko/hanko-elements";
    import SessionExpiredModal from "./SessionExpiredModal.svelte";
    import { onMount } from "svelte";

    const hankoAPI = import.meta.env.VITE_HANKO_API;
    const hankoClient = new Hanko(hankoAPI);

    const navigate = useNavigate();

    let showModal = false;
    let error: Error | null = null;

    const logout = () => {
        hankoClient.user
            .logout()
            .catch((e) => error = e);
    }

    const redirectToLogin = () => {
        navigate("/");
    }

    const redirectToTodos = () => {
        navigate("/todo");
    }

    onMount(() => {
        if (!hankoClient.session.isValid()) {
            redirectToLogin();
        }
    });
</script>

<SessionExpiredModal bind:showModal></SessionExpiredModal>
<nav class="nav">
    <button class="button" on:click|preventDefault={logout}>Logout</button>
    <button class="button" disabled>Profile</button>
    <button class="button" on:click|preventDefault={redirectToTodos}>Todos</button>
</nav>
<div class="content">
    <h1 class="headline">Profile</h1>
    {#if error}
        <div class="error">{ error?.message }</div>
    {/if}
    <hanko-profile on:onUserLoggedOut={redirectToLogin}></hanko-profile>
</div>

// frontend/examples/nextjs-app/app/profile/page.tsx
"use client";

import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import styles from "../../styles/Todo.module.css";

import { Hanko } from "@teamhanko/hanko-elements";
import HankoProfile from "../../components/HankoProfile";
import { SessionExpiredModal } from "../../components/SessionExpiredModal";

export default function Profile() {
  const router = useRouter();
  const [hankoClient, setHankoClient] = useState<Hanko>();
  const modalRef = useRef<HTMLDialogElement>(null);
  const [error, setError] = useState<Error | null>(null);
  const api = process.env.NEXT_PUBLIC_HANKO_API!;

  const logout = () => {
    hankoClient?.user.logout().catch((e) => {
      setError(e);
    });
  };

  const redirectToTodos = () => {
    router.push("/todo");
  };

  const redirectToLogin = useCallback(() => {
    router.push("/");
  }, [router]);

  useEffect(() => {
    if (!hankoClient) {
      return;
    }

    if (!hankoClient.session.isValid()) {
      redirectToLogin();
    }
  }, [hankoClient, redirectToLogin]);

  useEffect(() => {
    setHankoClient(new Hanko(api));
  }, [api]);

  useEffect(() => {
    if (hankoClient) {
      hankoClient.onUserLoggedOut(() => {
        redirectToLogin();
      });
    }
  }, [hankoClient, redirectToLogin]);

  useEffect(() => {
    if (hankoClient) {
      hankoClient.onSessionExpired(() => {
        modalRef.current?.showModal();
      });
    }
  }, [hankoClient]);

  return (
    <>
      <SessionExpiredModal ref={modalRef} />
      <nav className={styles.nav}>
        <button onClick={logout} className={styles.button}>
          Logout
        </button>
        <button disabled className={styles.button}>
          Profile
        </button>
        <button onClick={redirectToTodos} className={styles.button}>
          Todos
        </button>
      </nav>
      <div className={styles.content}>
        <h1 className={styles.headline}>Profile</h1>
        <div className={styles.error}>{error?.message}</div>
        <HankoProfile setError={setError} />
      </div>
    </>
  );
}
