// examples/vue/src/components/HankoAuth.vue
<script setup>
import { useRouter } from "vue-router";
import { register, testString } from "@teamhanko/hanko-elements";
import { onMounted } from "vue";

onMounted(() => {
  register({ shadow: true }).catch((e) => console.error(e));
});

const api = import.meta.env.VITE_HANKO_API;

const router = useRouter();

const redirectToTodo = () => {
  router.push({ path: "/todo" });
};
</script>

<template>
  <h1>Hello from { testString }</h1>
  <hanko-auth @hankoAuthSuccess="redirectToTodo" :api="api" />
</template>

// examples/react/src/HankoAuth.tsx
import React, { useCallback, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { register, testString } from "@teamhanko/hanko-elements";
import styles from "./Todo.module.css";

const api = process.env.REACT_APP_HANKO_API!;

function HankoAuth() {
  const navigate = useNavigate();

  const redirectToTodos = useCallback(() => {
    navigate("/todo", { replace: true });
  }, [navigate]);

  useEffect(() => {
    register({ shadow: true }).catch((e) => console.error(e));
    document.addEventListener("hankoAuthSuccess", redirectToTodos);
    return () =>
      document?.removeEventListener("hankoAuthSuccess", redirectToTodos);
  }, [redirectToTodos]);

  return (
    <div className={styles.content}>
      <h1>Hello from {testString}</h1>
      <hanko-auth api={api} />
    </div>
  );
}

export default HankoAuth;
