// examples/angular/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { environment } from '../../environments/environment';
import { Router } from '@angular/router';
import { register } from '@teamhanko/hanko-elements';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['../app.component.css']
})
export class LoginComponent {
  api = environment.hankoApi;
  error: Error | undefined;

  constructor(private router: Router) {
    register({shadow: true}).catch((e) => this.error = e);
  }

  redirectToTodo() {
    this.router.navigate(['/todo']).catch((e) => this.error = e);
  }
}

<div class="content">
  <div class="error">{{ error?.message }}</div>
  <hanko-auth
    (hankoAuthSuccess)="redirectToTodo()"
    [api]="api"
  ></hanko-auth>
</div>

// frontend/examples/svelte/src/lib/Login.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { useNavigate } from "svelte-navigator";
  import { register } from '@teamhanko/hanko-elements';

  const api = import.meta.env.VITE_HANKO_API;

  const navigate = useNavigate();
  let element;

  const redirectToTodos = () => {
    navigate('/todo');
  };

  let error: Error | null = null;

  onMount(async () => {
    register({ shadow: true }).catch((e) => error = e);
    element?.addEventListener('hankoAuthSuccess', redirectToTodos);
  });

  onDestroy(() => {
    element?.removeEventListener('hankoAuthSuccess', redirectToTodos);
  });
</script>

<div class="content">
  {#if error}
    <div class="error">{ error?.message }</div>
  {/if}
  <hanko-auth bind:this={element} {api}/>
</div>
