// frontend/examples/angular/src/app/login/login.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HankoService } from "../services/hanko.services";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['../app.component.css']
})
export class LoginComponent implements OnInit, OnDestroy {
  error: Error | undefined;

  constructor(private hankoService: HankoService, private router: Router) {}

  ngOnInit() {
    this.hankoService.register().catch((e) => this.error = e);
    this.hankoService.client.onAuthFlowCompleted(() => this.redirectToTodo())
  }

  ngOnDestroy() {
    this.hankoService.client.removeEventListeners();
  }

  redirectToTodo() {
    this.router.navigate(['/todo']).catch((e) => this.error = e);
  }
}

<div class="content">
  <div class="error">{{ error?.message }}</div>
  <hanko-auth></hanko-auth>
</div>

// frontend/examples/svelte/src/lib/Login.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { useNavigate } from "svelte-navigator";
  import { createHankoClient, register } from '@teamhanko/hanko-elements';

  const api = import.meta.env.VITE_HANKO_API;
  const hankoClient = createHankoClient(api);

  const navigate = useNavigate();

  const redirectToTodos = () => {
    navigate('/todo');
  };

  let error: Error | null = null;

  onMount(() => {
    register(api).catch((e) => error = e);
    hankoClient.onAuthFlowCompleted(redirectToTodos);
  });

  onDestroy(() => {
    hankoClient.removeEventListeners();
  });
</script>

<div class="content">
  {#if error}
    <div class="error">{ error?.message }</div>
  {/if}
  <hanko-auth />
</div>
