// frontend/examples/nextjs/pages/profile.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { NextPage } from "next";
import { useRouter } from "next/router";
import dynamic from "next/dynamic";
import styles from "../styles/Todo.module.css";
import { Hanko } from "@teamhanko/hanko-elements";
import { SessionExpiredModal } from "../components/SessionExpiredModal";

const hankoAPI = process.env.NEXT_PUBLIC_HANKO_API!;

const HankoProfile = dynamic(() => import("../components/HankoProfile"), {
  ssr: false,
});

const Todo: NextPage = () => {
  const router = useRouter();
  const hankoClient = useMemo(() => new Hanko(hankoAPI), []);
  const modalRef = useRef<HTMLDialogElement>(null);
  const [error, setError] = useState<Error | null>(null);

  const logout = () => {
    hankoClient.user
      .logout()
      .catch((e) => {
        setError(e);
      });
  };

  const redirectToTodos = () => {
    router.push("/todo").catch((e) => setError(e));
  };

  const redirectToLogin = useCallback(() => {
    router.push("/").catch(setError)
  }, [router]);

  useEffect(() => hankoClient.onUserLoggedOut(() => {
    redirectToLogin();
  }), [hankoClient, redirectToLogin]);

  useEffect(() => hankoClient.onSessionNotPresent(() => {
    redirectToLogin();
  }), [hankoClient, redirectToLogin]);

  useEffect(() => hankoClient.onSessionExpired(() => {
    modalRef.current?.showModal();
  }), [hankoClient]);

  return (
    <>
      <SessionExpiredModal ref={modalRef} />
      <nav className={styles.nav}>
        <button onClick={logout} className={styles.button}>
          Logout
        </button>
        <button disabled className={styles.button}>
          Profile
        </button>
        <button onClick={redirectToTodos} className={styles.button}>
          Todos
        </button>
      </nav>
      <div className={styles.content}>
        <h1 className={styles.headline}>Profile</h1>
        <div className={styles.error}>{error?.message}</div>
        <HankoProfile setError={setError} />
      </div>
    </>
  );
};

export default Todo;

// frontend/examples/svelte/src/lib/Profile.svelte
<script lang="ts">
    import { useNavigate } from "svelte-navigator";
    import { Hanko } from "@teamhanko/hanko-elements";
    import SessionExpiredModal from "./SessionExpiredModal.svelte";

    const hankoAPI = import.meta.env.VITE_HANKO_API;
    const hankoClient = new Hanko(hankoAPI);

    const navigate = useNavigate();

    let showModal = false;
    let error: Error | null = null;

    const logout = () => {
        hankoClient.user
            .logout()
            .catch((e) => error = e);
    }

    const redirectToLogin = () => {
        navigate("/");
    }

    const redirectToTodos = () => {
        navigate("/todo");
    }
</script>

<SessionExpiredModal bind:showModal></SessionExpiredModal>
<nav class="nav">
    <button class="button" on:click|preventDefault={logout}>Logout</button>
    <button class="button" disabled>Profile</button>
    <button class="button" on:click|preventDefault={redirectToTodos}>Todos</button>
</nav>
<div class="content">
    <h1 class="headline">Profile</h1>
    {#if error}
        <div class="error">{ error?.message }</div>
    {/if}
    <hanko-profile on:onSessionNotPresent={redirectToLogin} on:onUserLoggedOut={redirectToLogin}></hanko-profile>
</div>
