// frontend/examples/angular/src/app/profile/profile.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { TodoService } from '../services/todo.service';
import { HankoService } from "../services/hanko.services";

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['../app.component.css'],
})
export class ProfileComponent implements OnInit, OnDestroy {
  error: Error | undefined;

  constructor(private hankoService: HankoService, private todoService: TodoService, private router: Router) {}

  ngOnInit() {
    this.hankoService.register().catch((e) => this.error = e);
    this.hankoService.client.onSessionRemoved(() => {
      this.redirectToLogin();
    });
  }

  ngOnDestroy() {
    this.hankoService.client.removeEventListeners();
  }

  logout() {
    this.hankoService.client.user.logout()
      .catch((e) => (this.error = e));
  }

  redirectToLogin() {
    this.router.navigate(['/']).catch((e) => (this.error = e));
  }

  redirectToTodos() {
    this.router.navigate(['/todo']).catch((e) => (this.error = e));
  }
}

<nav class="nav">
  <button (click)="logout()" class="button">Logout</button>
  <button disabled class="button">Profile</button>
  <button (click)="redirectToTodos()" class="button">Todos</button>
</nav>
<div class="content">
  <div class="error">{{ error?.message }}</div>
  <hanko-profile></hanko-profile>
</div>

// frontend/examples/svelte/src/lib/Profile.svelte
<script lang="ts">
    import { onDestroy, onMount } from "svelte";
    import { useNavigate } from "svelte-navigator";
    import { createHankoClient, register } from "@teamhanko/hanko-elements";

    const hankoAPI = import.meta.env.VITE_HANKO_API;
    const hankoClient = createHankoClient(hankoAPI);

    const navigate = useNavigate();

    let error: Error | null = null;

    onMount(() => {
        register(hankoAPI).catch((e) => error = e);
        hankoClient.onSessionRemoved(redirectToLogin);
    });

    onDestroy(() => {
        hankoClient.removeEventListeners();
    });

    const logout = () => {
        hankoClient.user
            .logout()
            .catch((e) => error = e);
    }

    const redirectToLogin = () => {
        navigate("/");
    }

    const redirectToTodos = () => {
        navigate("/todo");
    }
</script>

<nav class="nav">
    <button class="button" on:click|preventDefault={logout}>Logout</button>
    <button class="button" disabled>Profile</button>
    <button class="button" on:click|preventDefault={redirectToTodos}>Todos</button>
</nav>
<div class="content">
    <h1 class="headline">Profile</h1>
    {#if error}
        <div class="error">{ error?.message }</div>
    {/if}
    <hanko-profile />
</div>
