// frontend/examples/react/src/SessionExpiredModal.tsx
import { forwardRef, useCallback } from "react";
import { useNavigate } from "react-router-dom";

export const SessionExpiredModal = forwardRef<HTMLDialogElement>(
  (props, ref) => {
    const navigate = useNavigate();

    const redirectToLogin = useCallback(() => {
      navigate("/");
    }, [navigate]);

    return (
      <dialog ref={ref}>
        Please login again.
        <br />
        <br />
        <button onClick={redirectToLogin}>Login</button>
      </dialog>
    );
  }
);

// frontend/examples/svelte/src/lib/SessionExpiredModal.svelte
<script lang="ts">
  import { useNavigate } from "svelte-navigator";

  const navigate = useNavigate();

  let dialog: HTMLDialogElement; // HTMLDialogElement

  const redirectToLogin = () => {
    navigate("/");
  }

  export const openSessionExpiredModal = () => {
    dialog.showModal();
  }
</script>

<hanko-events on:onSessionExpired={openSessionExpiredModal}></hanko-events>
<dialog bind:this={dialog}>
  Please login again.<br /><br />
  <button on:click={redirectToLogin}>Login</button>
</dialog>
