// frontend/examples/angular/src/app/todo/todo.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Todos, TodoService } from '../services/todo.service';
import { HankoService } from "../services/hanko.services";

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['../app.component.css', './todo.component.css'],
})
export class TodoComponent implements OnInit, OnDestroy {
  todos: Todos = [];
  error: Error | undefined;
  description = '';

  changeDescription(event: any) {
    this.description = event.target.value;
  }

  changeCheckbox(event: any) {
    const { currentTarget } = event;
    this.patchTodo(currentTarget.value, currentTarget.checked);
  }

  constructor(private hankoService: HankoService, private todoService: TodoService, private router: Router) {}

  ngOnInit(): void {
    this.listTodos();
    this.hankoService.client.onSessionRemoved(() => {
      this.redirectToLogin();
    });
  }

  ngOnDestroy() {
    this.hankoService.client.removeEventListeners();
  }

  addTodo(event: any) {
    event.preventDefault();
    const entry = { description: this.description, checked: false };

    this.todoService
      .addTodo(entry)
      .then((res) => {
        if (res.status === 401) {
          this.redirectToLogin();
          return;
        }

        this.description = '';
        this.listTodos();

        return;
      })
      .catch((e) => {
        this.error = e;
      });
  }

  patchTodo(id: string, checked: boolean) {
    this.todoService
      .patchTodo(id, checked)
      .then((res) => {
        if (res.status === 401) {
          this.redirectToLogin();
          return;
        }

        this.listTodos();

        return;
      })
      .catch((e) => {
        this.error = e;
      });
  }

  listTodos() {
    this.todoService
      .listTodos()
      .then((res) => {
        if (res.status === 401) {
          this.redirectToLogin();
          return;
        }

        return res.json();
      })
      .then((todo) => {
        if (todo) {
          this.todos = todo;
        }
      })
      .catch((e) => {
        this.error = e;
      });
  }

  deleteTodo(id: string) {
    this.todoService
      .deleteTodo(id)
      .then((res) => {
        if (res.status === 401) {
          this.redirectToLogin();
          return;
        }

        this.listTodos();

        return;
      })
      .catch((e) => {
        this.error = e;
      });
  }

  logout() {
    this.hankoService.client.user
      .logout()
      .catch((e) => this.error = e);
  }

  redirectToLogin() {
    this.router.navigate(['/']).catch((e) => (this.error = e));
  }

  redirectToProfile() {
    this.router.navigate(['/profile']).catch((e) => (this.error = e));
  }
}

<nav class="nav">
  <button (click)="logout()" class="button">Logout</button>
  <button (click)="redirectToProfile()" class="button">Profile</button>
  <button disabled class="button">Todos</button>
</nav>
<div class="content">
  <h1 class="headline">Todos</h1>
  <div class="error">{{ error?.message }}</div>
  <form (submit)="addTodo($event)" class="form">
    <input
      required
      class="input"
      type="text"
      value="{{ description }}"
      (change)="changeDescription($event)"
    />
    <button type="submit" class="button">+</button>
  </form>
  <div class="list">
    <div *ngFor="let todo of todos" class="item">
      <input
        class="checkbox"
        id="{{ todo.todoID }}"
        type="checkbox"
        value="{{ todo.todoID }}"
        [checked]="todo.checked"
        (change)="changeCheckbox($event)"
      />
      <label class="description" for="{{ todo.todoID }}">{{
        todo.description
      }}</label>
      <button class="button" (click)="deleteTodo(todo.todoID!)">×</button>
    </div>
  </div>
</div>

// frontend/examples/nextjs/pages/todo.tsx
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { NextPage } from "next";
import { useRouter } from "next/router";
import { TodoClient, Todos } from "../util/TodoClient";
import styles from "../styles/Todo.module.css";
import { createHankoClient } from "@teamhanko/hanko-elements";

const hankoAPI = process.env.NEXT_PUBLIC_HANKO_API!;
const todoAPI = process.env.NEXT_PUBLIC_TODO_API!;

const Todo: NextPage = () => {
  const hankoClient = useMemo(() => createHankoClient(hankoAPI), []);
  const todoClient = useMemo(() => new TodoClient(todoAPI), []);
  const router = useRouter();

  const [todos, setTodos] = useState<Todos>([]);
  const [description, setDescription] = useState<string>("");
  const [error, setError] = useState<Error | null>(null);

  const redirectToProfile = () => {
    router.push("/profile").catch(setError)
  }

  const redirectToLogin = useCallback(() => {
    router.push("/").catch(setError)
  }, [router]);

  const addTodo = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const todo = { description, checked: false };

    todoClient
      .addTodo(todo)
      .then((res) => {
        if (res.status === 401) {
          redirectToLogin();
          return;
        }

        setDescription("");
        listTodos();

        return;
      })
      .catch((e) => {
        setError(e);
      });
  };

  const listTodos = useCallback(() => {
    todoClient
      .listTodos()
      .then((res) => {
        if (res.status === 401) {
          redirectToLogin();
          return;
        }

        return res.json();
      })
      .then((todo) => {
        if (todo) {
          setTodos(todo);
        }
      })
      .catch((e) => {
        setError(e);
      });
  }, [todoClient, redirectToLogin]);

  const patchTodo = (id: string, checked: boolean) => {
    todoClient
      .patchTodo(id, checked)
      .then((res) => {
        if (res.status === 401) {
          redirectToLogin();
          return;
        }

        listTodos();

        return;
      })
      .catch((e) => {
        setError(e);
      });
  };

  const deleteTodo = (id: string) => {
    todoClient
      .deleteTodo(id)
      .then((res) => {
        if (res.status === 401) {
          redirectToLogin();
          return;
        }

        listTodos();

        return;
      })
      .catch((e) => {
        setError(e);
      });
  };

  const logout = () => {
    hankoClient.user
      .logout()
      .catch((e) => {
        setError(e);
      });
  };

  const changeDescription = (event: React.ChangeEvent<HTMLInputElement>) => {
    setDescription(event.currentTarget.value);
  };

  const changeCheckbox = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { currentTarget } = event;
    patchTodo(currentTarget.value, currentTarget.checked);
  };

  useEffect(() => hankoClient.onSessionRemoved(() => {
    redirectToLogin();
  }), [hankoClient, redirectToLogin]);

  useEffect(() => {
    listTodos();
  }, [listTodos]);

  return (
    <>
      <nav className={styles.nav}>
        <button onClick={logout} className={styles.button}>
          Logout
        </button>
        <button onClick={redirectToProfile} className={styles.button}>
          Profile
        </button>
        <button disabled className={styles.button}>
          Todos
        </button>
      </nav>
      <div className={styles.content}>
        <h1 className={styles.headline}>Todos</h1>
        <div className={styles.error}>{error?.message}</div>
        <form onSubmit={addTodo} className={styles.form}>
          <input
            required
            className={styles.input}
            type={"text"}
            value={description}
            onChange={changeDescription}
          />
          <button type={"submit"} className={styles.button}>
            +
          </button>
        </form>
        <div className={styles.list}>
          {todos.map((todo, index) => (
            <div className={styles.item} key={index}>
              <input
                className={styles.checkbox}
                id={todo.todoID}
                type={"checkbox"}
                value={todo.todoID}
                checked={todo.checked}
                onChange={changeCheckbox}
              />
              <label className={styles.description} htmlFor={todo.todoID}>
                {todo.description}
              </label>
              <button className={styles.button} onClick={() => deleteTodo(todo.todoID!)}>
                ×
              </button>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default Todo;
