// frontend/examples/vue/src/components/HankoAuth.vue
<script setup lang="ts">
import { useRouter } from "vue-router";
import { register } from "@teamhanko/hanko-elements";
import { onMounted } from "vue";

const router = useRouter();
const api = import.meta.env.VITE_HANKO_API;
const emit = defineEmits(["on-error"]);

const redirectToTodo = () => {
  router.push({ path: "/todo" });
};

onMounted(() => {
  register({ shadow: true }).catch((e) => emit("on-error", e));
});
</script>

<template>
  <hanko-auth @hankoAuthSuccess="redirectToTodo" :api="api" />
</template>

// examples/nextjs/components/HankoAuth.tsx
import { register } from "@teamhanko/hanko-elements";
import { useCallback, useEffect } from "react";
import { useRouter } from "next/router";

const api = process.env.NEXT_PUBLIC_HANKO_API!;

function HankoAuth() {
  const router = useRouter();

  const redirectToTodos = useCallback(() => {
    router.replace("/todo");
  }, [router]);

  useEffect(() => {
    register({ shadow: true }).catch((e) => console.error(e));
  }, []);

  useEffect(() => {
    document.addEventListener("hankoAuthSuccess", redirectToTodos);
    return () =>
      document.removeEventListener("hankoAuthSuccess", redirectToTodos);
  }, [redirectToTodos]);

  return <hanko-auth api={api} lang="en"/>;
}

export default HankoAuth;
