// frontend/examples/svelte/src/lib/Login.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { useNavigate } from "svelte-navigator";
  import { register } from '@teamhanko/hanko-elements';

  const api = import.meta.env.VITE_HANKO_API;

  const navigate = useNavigate();
  let element;

  const redirectToTodos = () => {
    navigate('/todo');
  };

  let error: Error | null = null;

  onMount(async () => {
    register({ shadow: true }).catch((e) => error = e);
    element?.addEventListener('hankoAuthSuccess', redirectToTodos);
  });

  onDestroy(() => {
    element?.removeEventListener('hankoAuthSuccess', redirectToTodos);
  });
</script>

<div class="content">
  {#if error}
    <div class="error">{ error?.message }</div>
  {/if}
  <hanko-auth bind:this={element} {api}/>
</div>

// frontend/examples/fresh/islands/Login.tsx
import { HANKO_API_URL } from "../config.ts";

const code = `
  import { register } from 'https://esm.sh/@teamhanko/hanko-elements@0.10.0';

  register('${HANKO_API_URL}', { shadow: true });
  document.addEventListener('hankoAuthSuccess', (event) => {
    document.location.href = '/todo';
  });
`;

export default function Login() {
  return (
    <div>
      <hanko-auth api={HANKO_API_URL}></hanko-auth>
      <script type="module">
        {code}
      </script>
    </div>
  );
}
