// examples/nextjs/components/HankoProfile.tsx
import { register } from "@teamhanko/hanko-elements";
import { useCallback, useEffect } from "react";
import { useRouter } from "next/router";

const api = process.env.NEXT_PUBLIC_HANKO_API!;

interface Props {
  setError(error: Error): void;
}

function HankoProfile({ setError }: Props) {
  useEffect(() => {
    register({ shadow: true }).catch(setError);
  }, [setError]);

  return <hanko-profile api={api} />;
}

export default HankoProfile;

// frontend/examples/vue/src/components/HankoProfile.vue
<script setup lang="ts">
import { register } from "@teamhanko/hanko-elements";
import { onMounted } from "vue";

const api = import.meta.env.VITE_HANKO_API;
const emit = defineEmits(["on-error"]);

onMounted(() => {
  register({ shadow: true }).catch((e) => emit("on-error", e));
});
</script>

<template>
  <hanko-profile :api="api" />
</template>
