// frontend/examples/vue/src/components/HankoProfile.vue
<script setup lang="ts">
import { register } from "@teamhanko/hanko-elements";
import { onMounted } from "vue";

const api = import.meta.env.VITE_HANKO_API;
const emit = defineEmits(["on-error"]);

onMounted(() => {
  register(api).catch((e) => emit("on-error", e));
});
</script>

<template>
  <hanko-profile />
</template>

// frontend/examples/nextjs-app/components/HankoProfile.tsx
"use client";

import { register } from "@teamhanko/hanko-elements";
import { useEffect } from "react";

interface Props {
  setError(error: Error): void;
}

function HankoProfile({ setError }: Props) {
  const api = process.env.NEXT_PUBLIC_HANKO_API!;

  useEffect(() => {
    register(api).catch(setError);
  }, [setError, api]);

  return <hanko-profile />;
}

export default HankoProfile;
