// frontend/examples/vue/src/components/SessionExpiredModal.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();
const modal = ref<HTMLDialogElement>();
const error = ref<Error>();

const show = () => {
  modal.value?.showModal();
};

const redirectToLogin = () => {
  router.push("/").catch((e) => (error.value = e));
};

defineExpose({
  show,
});
</script>

<template>
  <hanko-events @onSessionExpired="show()"></hanko-events>
  <dialog ref="modal">
    <div class="error">{{ error?.message }}</div>
    Please login again.<br /><br />
    <button @click="redirectToLogin()">Login</button>
  </dialog>
</template>

// frontend/examples/nextjs/components/SessionExpiredModal.tsx
import { forwardRef, useCallback } from "react";
import { useRouter } from "next/router";

export const SessionExpiredModal = forwardRef<HTMLDialogElement>(
  (props, ref) => {
    const router = useRouter();

    const redirectToLogin = useCallback(() => {
      router.push("/");
    }, [router]);

    return (
      <dialog ref={ref}>
        Please login again.
        <br />
        <br />
        <button onClick={redirectToLogin}>Login</button>
      </dialog>
    );
  }
);

SessionExpiredModal.displayName = "SessionExpiredModal"
